import type { Metadata } from "next";
import { Sofia_Sans, Rubik } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { MainNavigation } from "@/ui/navigation/MainNavigation";
import { MainFooter } from "@/ui/footer/MainFooter";

const sofiaSans = Sofia_Sans({
  variable: "--font-sofia-sans",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sofiaSans.variable} ${rubik.variable} grid justify-between antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Admin Bar + Navigation */}
          <MainNavigation />

          {children}

          {/* Footer */}
          <MainFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
